### PR TITLE
fix(sticky-directive): fix element jumping

### PR DESCRIPTION
**Pull request by aleesaan**
Fixed the calculations to determine the sticky status, thus fixing the bug mentioned [here](https://github.com/w11k/angular-sticky-things/pull/10#issuecomment-444082749).

### CODE REVIEW

**Comment by CanKattwinkel** [comment]
Ah, there is still a bug. If the marginTop is changed it will jump. This was the bug I intended to fix, but I introduced a jump for initial set marginTops.

Reproduce:
1. http://localhost:4200/dev
1. Set marginTop to 50 by using the input
1. `window.scrollTo(0,490);`

-> StickyThing is not yet moved, should have a top of 40 pixels.

If you scroll to `window.scrollTo(0,502);`it will then perform the jump. This also happens to me on "normal" scroll - btw i am working in Chromium.


Also a hint, you can use the existing e2e tests. I'm not too experienced with e2e in Angular yet, but there are some. I usually have them running in the background while working on this. (`npm run e2e-watch-no-serve`). Also, import the module relative (not from dist) in your app module in order to get live reload during dev.

**Comment by aleesaan** [comment]
Also, I just added a fix to include the sticky element's margins in the calculations for the spacer's height. Before, if you had margins on the sticky element, it would cause the element below to jump, because the spacer's height wouldn't take those margins into account.

Additionally, if you're wondering why I had to store them in variables when initializing it, think of a case where you have a top menu that has a margin bottom to separate from the rest of the content. When it becomes sticky, you (most likely) will add something like `&.is-sticky { margin-bottom: 0 }`, otherwise the things under those margins will be visible but unclickable. To prevent the calculations to be affected by the new (`is-sticky`) styles, we need to store the initial values (which are the only ones we care about) and use those when doing calculations for the spacer.

Let me know what you think!

**Comment by CanKattwinkel** [comment]
I think at some point we should be able to handle changing margins, but for now it is more important to not jump on the initial setted margin. You agree?

So I'd merge this and then I want to do some refactoring - moving all the input to input streams that act as sinks for any event that might affect the stickyness. Removing the need for any OnChanges (in fact I think the Angular lifecylces will become rx based at some point).

**Comment by CanKattwinkel** [comment]
@aleesaan ci run right after this PR, v1.0.6

Just published the demo manually

**Pull request merged**
