### PR TITLE
directive will now output events when changing sticky status

### PR DESCRIPTION
**Pull request by CapitanFindusFI**
this should allow events handling when stickyThings directive changes its own status. allowing to subscribe for 3 different events:
`stickyUnset` when sticky status gets removed
`stickySet` when sticky status gets attached
`stickyChange` when sticky status gets toggled

### CODE REVIEW

**Comment by CanKattwinkel** [comment]
Hi @CapitanFindusFI, thank you very much for contributing to sticky-things. We'll take a closer look and merge it soon.

 I'll make some notes in here since another employee will do handle the release.


- Chery Pick / Merge into Dev
- Create Release with Git Flow: https://github.com/w11k/angular-sticky-things/blob/master/DEVELOPING.md#release
- Pipeline and so on lives here https://gitlab.com/w11k-gitlab/angular-sticky-things

**Comment by HighTide** [comment]
is there any progress on this?

**Comment by HighTide** [comment]
is there any progress on this?

**Comment by tobiasatw11k** [comment]
@HighTide @CapitanFindusFI yes, i adjusted the outputs a little bit, as the events are sent on every screen move you always know if an element is sticky or not and therefore also when the status changes. additionally a second attribute reachedLowerEdge is available, which tells you if the sticky element is still visible or out of screen. for further information see [#37](https://github.com/w11k/angular-sticky-things/issues/37)

**Pull request closed without merging**
