### PR TITLE
feat(sticky-directive): add enable flag

### PR DESCRIPTION
**Pull request by aleesaan**
Added an `enable` input that can be used to dynamically activate/deactivate the directive.

### CODE REVIEW

**Comment by aleesaan** [comment]
I actually was trying to do a PR into my fork, but I got confused an opened it here :sweat_smile:
I'm gonna have a final look at it tomorrow morning to finalize it and then I'll reopen the PR!

**Comment by aleesaan** [comment]
I reopened but I'm still not 100% sure - I moved the initialization to `OnInit` and everything seems to be working fine, but what do you think about this?
I'm going to investigate a bit more tomorrow, for now I wanted to reopen it so to have the latest commits.

**Comment by CanKattwinkel** [comment]
I'll look into it on Friday and do some testing, but it looks good to me! Thanks for your contributing. 

Something I'd change is to use getter/setter on @Input() to have better control. Instead of the onChanges Interface:
https://www.thecodecampus.de/blog/call-a-method-when-input-changes/

**Comment by aleesaan** [comment]
Thanks for your suggestion, it's an interesting technique! I just gave it a try, moving the activation logic (`value ? this.activate() : this.deactivate()`) inside the setter; yet I'm not sure it's correct in our case, since it gets called too early (i.e. at the first `OnChanges`), and it also makes it harder to set a default `enable = true`.
Instead, maybe we should leverage the `OnInit` lifecycle (at first) in combination with `!enableChanged.firstChange` (afterwards) to trigger the activation logic when needed.

**Comment by aleesaan** [comment]
Just removed two lint error rules as I didn't want to change the code, but if you prefer you can revert that and change the code instead. Those errors kept bugging me 😅

**Comment by CanKattwinkel** [comment]
I've added some test and merged it to develop, then I realized I introduced a new bug with marignTop.. If you look at the `/` page you'll see that spacer3 element starts being sticky way too early..

Hopefully I'll be able to look into this issue soon and then do the release!

**Pull request closed without merging**
